# -*- coding: utf-8 -*-

"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app
"""

import re
from setuptools import setup

FRAMEWORKS = ['/usr/local/opt/csfml/lib/libcsfml-window.2.3.dylib',
              '/usr/local/opt/csfml/lib/libcsfml-graphics.2.3.dylib',
              '/usr/local/opt/csfml/lib/libcsfml-audio.2.3.dylib',
              '/usr/local/opt/csfml/lib/libcsfml-system.2.3.dylib']

OPTIONS = {'iconfile': 'bundle_res/App.icns',
           'frameworks': FRAMEWORKS}

setup(
    app=['dummy.py'],
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
